
package determinista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.OptionPaneUI;

/**
 *
 * @author david
 */
public class Interfaz extends javax.swing.JFrame {

    ArrayList<String> aErrores;
    ArrayList<String> aLexemas;
    ArrayList<String> aTokens;
    
    int estado;
    int indice;
    String lexema;
    
    private void varinit(){ //Iniciar variables
        indice = 0;
        estado = 0;
        lexema = "";
        
        aErrores = new ArrayList();
        aLexemas = new ArrayList();
        aTokens = new ArrayList();
    }
    
    private void analizar(){
        String entrada = txt_entrada.getText()+" ";
        String limpiartxt = "";
        int err = 0;
        for(int i = 0; i < entrada.length();i++){
            char letra = entrada.charAt(i);
            switch(letra){
                case '\r':
                case '\t':
                case '\n':
                case '\b':
                case '\f':
                case ' ':
                    break;
                    
                default:
                    limpiartxt = limpiartxt + letra;
                    
            }
        }
        
        for(indice = 0; indice<limpiartxt.length();indice++){
                char letra = limpiartxt.charAt(indice);
                //int ascii = letra;
                
                switch(estado){
                    case 0:
                        if(letra == 'a'){
                            estado = 0;
                            lexema = "" + letra;
                        } else if(letra == 'e'){
                            estado = 1;
                            lexema = "" + letra;
                        } else{
                            System.out.println("ERROR LEXICO \"" +letra + "\" columna: " + indice);
                            estado = 14;
                            aErrores.add(""+letra);
                        }
                    break;     
                
                case 1:
                    if(letra == 'e'){
                        estado = 1;
                        lexema = "" + letra;
                    } else if (letra == 'i'){
                         estado = 2;
                        lexema = "" + letra;
                    }else{
                            System.out.println("ERROR LEXICO \"" +letra + "\" columna: " + indice);
                            estado = 14;
                            aErrores.add(""+letra);
                    }
                    break;
                
                case 2:
                    if(letra == 'o'){
                        estado = 3;
                        lexema = "" + letra;
                    }else{
                            System.out.println("ERROR LEXICO \"" +letra + "\" columna: " + indice);
                            estado = 14;
                            aErrores.add(""+letra);
                    }
                    break;
                    
                case 3:
                    if(letra == 'u'){
                        estado = 4;
                        lexema = "" + letra;
                    }else{
                            System.out.println("ERROR LEXICO \"" + letra + "\" columna: " + indice);
                            estado = 14;
                            aErrores.add(""+letra);
                    }
                    break;
                    
                case 4:
                    if(letra == 'u'){
                        estado = 4;
                        lexema = "" + letra;
                    }else{
                        aLexemas.add(lexema);
                        lexema="";
                        estado = 14;
                        indice --;
                    }
                    break;
                    
                }
                if (estado == 14)
                {
                    JOptionPane.showMessageDialog(rootPane, "ERROR cadena de entrada no valida " ,"ERROR",JOptionPane.INFORMATION_MESSAGE);
                    estado = 0;
                    break;
                    
                }
        }
        
        
        if (aErrores.isEmpty()){
            System.out.println("Exito");
        }
    }
    
    private void printLexemas(){
            for (int i=0;i<aLexemas.size();i++){
                System.out.println(aLexemas.get(i));
            }
        }
    
    private void printErrores(){
        for (int i=0;i<aErrores.size();i++){
            System.out.println(aErrores.get(i));
        }
    }
    
    public Interfaz() {
        initComponents();
        varinit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_analizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_entrada = new javax.swing.JTextArea();
        btn_lexemas = new javax.swing.JButton();
        btn_errores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_analizar.setText("Analizar Cadena");
        btn_analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analizarActionPerformed(evt);
            }
        });

        txt_entrada.setColumns(20);
        txt_entrada.setRows(5);
        jScrollPane1.setViewportView(txt_entrada);
        txt_entrada.getAccessibleContext().setAccessibleName("");

        btn_lexemas.setText("Lexemas");
        btn_lexemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lexemasActionPerformed(evt);
            }
        });

        btn_errores.setText("Errores");
        btn_errores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_erroresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 57, Short.MAX_VALUE)
                        .addComponent(btn_analizar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_lexemas)
                        .addGap(18, 18, 18)
                        .addComponent(btn_errores)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_analizar)
                    .addComponent(btn_lexemas)
                    .addComponent(btn_errores))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analizarActionPerformed
        analizar();
    }//GEN-LAST:event_btn_analizarActionPerformed

    private void btn_lexemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lexemasActionPerformed
        printLexemas();
    }//GEN-LAST:event_btn_lexemasActionPerformed

    private void btn_erroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_erroresActionPerformed
        printErrores();
    }//GEN-LAST:event_btn_erroresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_analizar;
    private javax.swing.JButton btn_errores;
    private javax.swing.JButton btn_lexemas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_entrada;
    // End of variables declaration//GEN-END:variables
}
